name: magic_yeti
description: Magic The Gathering Tracking App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  api_client:
    path: packages/api_client
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.2
  cloud_firestore: ^4.15.5
  equatable: ^2.0.5
  firebase_core: ^2.25.3
  firebase_database: ^10.4.4
  firebase_database_repository:
    path: packages/firebase_database_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^13.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  provider: ^6.1.1
  scryfall_repository:
    path: packages/scryfall_repository

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
