// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDurTh4BqkJQmClz5jKY9xkZmjZFIRoJhY',
    appId: '1:370172089725:web:c20bb3cc0c965681ad6814',
    messagingSenderId: '370172089725',
    projectId: 'magic-yeti',
    authDomain: 'magic-yeti.firebaseapp.com',
    databaseURL: 'https://magic-yeti-default-rtdb.firebaseio.com',
    storageBucket: 'magic-yeti.appspot.com',
    measurementId: 'G-G4L2EVY7HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfZ5e-cbnu6YYfzIhs_E4K6LwhmUN84s',
    appId: '1:370172089725:android:26131762052d9ba0ad6814',
    messagingSenderId: '370172089725',
    projectId: 'magic-yeti',
    databaseURL: 'https://magic-yeti-default-rtdb.firebaseio.com',
    storageBucket: 'magic-yeti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUONDMUnjBNKlxCu6DzG0VHtWbwyUuCro',
    appId: '1:370172089725:ios:e5f69a3843833908ad6814',
    messagingSenderId: '370172089725',
    projectId: 'magic-yeti',
    databaseURL: 'https://magic-yeti-default-rtdb.firebaseio.com',
    storageBucket: 'magic-yeti.appspot.com',
    iosBundleId: 'com.crossout.org.magicyeti',
  );
}
